<div class="parent-slideshow-container">
    <div class="child-slideshow-container">
        <div class="slideshow-container">
            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::../images/banner-homepage_1.png'); ?>" alt="banner-homepage_1" class="img-banner">
            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::../images/banner-homepage_2.png'); ?>" alt="banner-homepage_2" class="img-banner">
            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::../images/banner-homepage_3.png'); ?>" alt="banner-homepage_3" class="img-banner">
            <div class="dot-container" style="text-align:center">
                <span class="dot"></span> 
                <span class="dot"></span> 
                <span class="dot"></span> 
            </div>
            <a class="prev" onclick="plusSlides(-1, 1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1, 1)">&#10095;</a>
        </div>
    </div>
</div>


<script type="text/javascript">
    require([ 
        'jquery', 
        'jquery/ui'
    ], function($){                      
        var slideIndex = 0;
        showSlides();

        function showSlides() {
            var i;
            var slides = document.getElementsByClassName("img-banner");
            var dots = document.getElementsByClassName("dot");
            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";  
            }
            slideIndex++;
            if (slideIndex > slides.length) {slideIndex = 1}    
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" active", "");
            }
            slides[slideIndex-1].style.display = "block";  
            dots[slideIndex-1].className += " active";
            setTimeout(showSlides, 2000); // Change image every 2 seconds
        }

        // var slideIndexes = [1,1];
        // var slideClass = ["img-banner"];	
        // showSlidesSide(1, 0);
        // showSlidesSide(1, 1);

        // function plusSlides(n, no) {
        //     showSlidesSide(slideIndexes[no] += n, no);
        // }

        // function showSlidesSide(n, no) {
        //     var i;
        //     var x = document.getElementsByClassName(slideClass[no]);
        //     if (n > x.length) {slideIndexes[no] = 1}    
        //     if (n < 1) {slideIndexes[no] = x.length}
        //     for (i = 0; i < x.length; i++) {
        //         x[i].style.display = "none";  
        //     }
        //     x[slideIndexes[no]-1].style.display = "block";  
        // }
    });
</script>